apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authServer.fullname" . }}
  labels:
    {{- include "authServer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "authServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authServer.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        env:
        - name: AUTH_SERVER__ENV_PREFIX
          value: {{ include "authServer.envPrefix" }}
        envFrom:
        - configMapRef:
            name: {{ include "authServer.fullname" . }}-env-config
          prefix: {{ include "authServer.envPrefix" }}
      volumes:
      - name: secrets
        secret:
          secretName: {{ include "authServer.fullname" . }}-secrets
