apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authServer.fullname" . }}-secrets
  labels:
    {{- include "authServer.labels" . | nindent 4 }}
type: Opaque
data:
  .PRIVATE.pem: |
    {{- .Values.secrets.privateKey | b64enc | quote | nindent 4 }}
  .PUBLIC.pem: |
    {{- .Values.secrets.publicKey | b64enc | quote | nindent 4 }}
