env: "local"
http_server:
  address: "localhost:8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 60s
  shutdown_timeout: 10s
  health_timeout: 1s
jwt:
  issuer: "Studopolis Authorization"
  access_ttl: 10m
  refresh_ttl: 60m
  leeway: 2s
storage:
  alpha:
    url: postgres://auth:auth@localhost:5432/postgres
    read_timeout: 5s
    write_timeout: 5s
