# Strictly use `kebab-case` for all keys

cors:
  allowed-origins:
    - "https://studopolis.ru"
  max-age: 600
http-server:
  address: "localhost:8080"
  read-timeout: 5s
  write-timeout: 5s
  idle-timeout: 60s
  shutdown-timeout: 10s
  health-timeout: 1s
jwt:
  issuer: "Studopolis Authentication"
  access-ttl: 15m
  refresh-ttl: 24h
  leeway: 2s
storage:
    url: "postgres://auth:0000@localhost:5432/master"
    read-timeout: 5s
    write-timeout: 5s
